IF DB_ID('CKCClassroom72') IS NOT NULL DROP DATABASE CKCClassroom72;
GO
CREATE DATABASE CKCClassroom008;
GO
use ckcclassroom008
GO

-- 2. USERS (Tài kho?n chung)
CREATE TABLE USERS (
    ID INT PRIMARY KEY IDENTITY,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    Quyen SMALLINT NOT NULL,         -- 0: SV, 1: GV, 2: Admin
    TrangThai SMALLINT NOT NULL,
    MaNguoiDung NVARCHAR(20),
    HoTen NVARCHAR(255),
    IsDeleted BIT DEFAULT 0
);

-- 3. KHOA, BOMON, MONHOC
CREATE TABLE KHOA (
    ID INT PRIMARY KEY IDENTITY,
    MaKhoa VARCHAR(20) UNIQUE,
    TenKhoa NVARCHAR(255) NOT NULL,
    IsDeleted BIT DEFAULT 0
);
CREATE TABLE BOMON (
    ID INT PRIMARY KEY IDENTITY,
    TenBM NVARCHAR(255) NOT NULL,
    MaKhoa INT NOT NULL,
    IsDeleted BIT DEFAULT 0,
    FOREIGN KEY (MaKhoa) REFERENCES KHOA(ID)
);
CREATE TABLE MONHOC (
    ID INT PRIMARY KEY IDENTITY,
    TenMH NVARCHAR(255) NOT NULL,
    TinChi SMALLINT,
    MaBM INT NOT NULL,
    IsDeleted BIT DEFAULT 0,
    FOREIGN KEY (MaBM) REFERENCES BOMON(ID)
);

CREATE TABLE LOPHOC (
    ID INT PRIMARY KEY IDENTITY,
	MaLop NVARCHAR(20) NULL,
    TenLop NVARCHAR(255) NOT NULL,
	NgayTao DateTime,
	MaBM INT,
    IsDeleted BIT DEFAULT 0
	
    FOREIGN KEY (MaBM) REFERENCES BOMON(ID)
);



-- 4. GIANGVIEN, SINHVIEN
CREATE TABLE GIANGVIEN (
    ID INT PRIMARY KEY IDENTITY,
	MaGV INT,
    HoGV NVARCHAR(255),
    TenGV NVARCHAR(255),
    NgaySinh DATETIME,
    GioiTinh SMALLINT,
    SDT VARCHAR(20),
    MaTK INT NOT NULL,
    CCCD NVARCHAR(20),
    MaBM INT NOT NULL,
    DiaChi NVARCHAR(255),
    TrangThai SMALLINT,
    MaGiangVien NVARCHAR(20),
    IsDeleted BIT DEFAULT 0,
    FOREIGN KEY (MaTK) REFERENCES USERS(ID),
    FOREIGN KEY (MaBM) REFERENCES BOMON(ID)
);

CREATE TABLE SINHVIEN (
    ID INT PRIMARY KEY IDENTITY,
    MaSinhVien VARCHAR(20),
    MaTK INT NOT NULL,
    HoTen NVARCHAR(255),
    NgaySinh DATETIME,
    GioiTinh SMALLINT,
    SDT VARCHAR(20),
    CCCD NVARCHAR(20),
    MaLopHoc INT,
    TrangThai SMALLINT,
    IsDeleted BIT DEFAULT 0,
    FOREIGN KEY (MaTK) REFERENCES USERS(ID)
    -- MaLopHoc: N?u mu?n qu?n lý theo l?p niên ch?, có th? t?o b?ng LOPHOC riêng
);

-- 5. LOPHOCPHAN, mapping nhi?u nhi?u
CREATE TABLE LOPHOCPHAN (
    ID INT PRIMARY KEY IDENTITY,
    TenLHP NVARCHAR(255) NOT NULL,
    NgayTao DATETIME,
    HocKy SMALLINT,
    ChinhSach SMALLINT,
    NamHoc INT,
    TrangThai SMALLINT,
    MaMH INT NOT NULL,
	MaGV INT,
    MaLH INT, 
	LuuTru SMALLINT,
    IsDeleted BIT DEFAULT 0,
    FOREIGN KEY (MaMH) REFERENCES MONHOC(ID),
	FOREIGN KEY (MaGV) REFERENCES GIANGVIEN(ID),
    FOREIGN KEY (MaLH) REFERENCES LOPHOC(ID)
);





-- Phân công nhi?u gi?ng viên 1 l?p h?c ph?n
CREATE TABLE GIANGVIEN_LHP (
    ID INT PRIMARY KEY IDENTITY,
    MaGV INT NOT NULL,
    MaLHP INT NOT NULL,
    TrangThai SMALLINT,
    FOREIGN KEY (MaGV) REFERENCES GIANGVIEN(ID),
    FOREIGN KEY (MaLHP) REFERENCES LOPHOCPHAN(ID)
);

-- Nhi?u sinh viên - nhi?u l?p h?c ph?n
CREATE TABLE SINHVIEN_LHP (
    ID INT PRIMARY KEY IDENTITY,
    MaSV INT NOT NULL,
    MaLHP INT NOT NULL,
    TrangThai SMALLINT,
    FOREIGN KEY (MaSV) REFERENCES SINHVIEN(ID),
    FOREIGN KEY (MaLHP) REFERENCES LOPHOCPHAN(ID)
);

-- 6. TAILIEU h?c t?p
CREATE TABLE TAILIEU (
    ID INT PRIMARY KEY IDENTITY,
    TieuDe NVARCHAR(255),
    MoTa TEXT,
    DuongDan NVARCHAR(255),
    MaLHP INT NOT NULL,
    MaGV INT NOT NULL,
    NgayTao DATETIME DEFAULT GETDATE(),
    TrangThai SMALLINT,
    IsDeleted BIT DEFAULT 0,
    FOREIGN KEY (MaLHP) REFERENCES LOPHOCPHAN(ID),
    FOREIGN KEY (MaGV) REFERENCES GIANGVIEN(ID)
);
-- 7. BAIVIET, NOPBAI, FILE, NHANXET
CREATE TABLE BAIVIET (
    ID INT PRIMARY KEY IDENTITY,
    TieuDe NVARCHAR(255),
    NoiDung TEXT,
    LoaiBV SMALLINT,               -- 0: Thông báo, 1: Bài t?p
    MaTK INT NOT NULL,
    MaLHP INT NOT NULL,
    NgayTao DATETIME DEFAULT GETDATE(),
    HanNop DATETIME NULL,
    TrangThai SMALLINT,
    MaBaiViet NVARCHAR(20),
    IsDeleted BIT DEFAULT 0,
    FOREIGN KEY (MaTK) REFERENCES USERS(ID),
    FOREIGN KEY (MaLHP) REFERENCES LOPHOCPHAN(ID)
);

ALTER TABLE BAIVIET ADD HanNop DATETIME NULL
CREATE TABLE [FILE] (
    ID INT PRIMARY KEY IDENTITY,
    MaFile NVARCHAR(20),
    TenFile NVARCHAR(255),
    DuongDan NVARCHAR(255),
    LoaiFile NVARCHAR(10),
    DungLuong FLOAT,
    TrangThai SMALLINT,
    MaBaiViet INT,
    MaTailieu INT,
    NgayTao DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (MaBaiViet) REFERENCES BAIVIET(ID),
    FOREIGN KEY (MaTailieu) REFERENCES TAILIEU(ID)
);
CREATE TABLE NOPBAI (
    ID INT PRIMARY KEY IDENTITY,
    MaSV INT NOT NULL,
    MaLHP INT NOT NULL,
    MaBaiViet INT NOT NULL,
    Diem FLOAT NULL,
    FileDinhKem NVARCHAR(255),
    VanBan TEXT,
    TrangThai SMALLINT,
    NgayNop DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (MaSV) REFERENCES SINHVIEN(ID),
    FOREIGN KEY (MaLHP) REFERENCES LOPHOCPHAN(ID),
    FOREIGN KEY (MaBaiViet) REFERENCES BAIVIET(ID)
);

CREATE TABLE NHANXET (
    ID INT PRIMARY KEY IDENTITY,
    NoiDung TEXT NOT NULL,
    NgayTao DATETIME DEFAULT GETDATE(),
    MaBV INT NOT NULL,
    MaTK INT NOT NULL,
    TenNguoiDung NVARCHAR(255),
    FOREIGN KEY (MaBV) REFERENCES BAIVIET(ID),
    FOREIGN KEY (MaTK) REFERENCES USERS(ID)
);
select*from nopbai
-- 8. TRIGGERS sinh mã t? ??ng cho các b?ng c?n thi?t
-- USERS
CREATE TRIGGER trg_USERS_AutoCode ON USERS AFTER INSERT AS
BEGIN
    UPDATE USERS SET MaNguoiDung = 
        CASE i.Quyen
            WHEN 0 THEN 'sv' + CAST(i.ID AS NVARCHAR(10))
            WHEN 1 THEN 'gv' + CAST(i.ID AS NVARCHAR(10))
            WHEN 2 THEN 'admin' + CAST(i.ID AS NVARCHAR(10))
            ELSE 'user' + CAST(i.ID AS NVARCHAR(10))
        END
    FROM USERS JOIN inserted i ON USERS.ID = i.ID
    WHERE USERS.MaNguoiDung IS NULL;
END;
-- GIANGVIEN
CREATE TRIGGER trg_GIANGVIEN_AutoCode ON GIANGVIEN AFTER INSERT AS
BEGIN
    UPDATE GIANGVIEN SET MaGiangVien = 'gv' + CAST(i.ID AS NVARCHAR(10))
    FROM GIANGVIEN JOIN inserted i ON GIANGVIEN.ID = i.ID
    WHERE GIANGVIEN.MaGiangVien IS NULL;
END;
-- SINHVIEN
CREATE TRIGGER trg_SINHVIEN_AutoCode ON SINHVIEN AFTER INSERT AS
BEGIN
    UPDATE SINHVIEN SET MaSinhVien = 'sv' + CAST(i.ID AS NVARCHAR(10))
    FROM SINHVIEN JOIN inserted i ON SINHVIEN.ID = i.ID
    WHERE SINHVIEN.MaSinhVien IS NULL;
END;
-- BAIVIET
CREATE TRIGGER trg_BAIVIET_AutoCode ON BAIVIET AFTER INSERT AS
BEGIN
    UPDATE BAIVIET SET MaBaiViet = 'bv' + CAST(i.ID AS NVARCHAR(10))
    FROM BAIVIET JOIN inserted i ON BAIVIET.ID = i.ID
    WHERE BAIVIET.MaBaiViet IS NULL;
END;
-- [FILE]
CREATE TRIGGER trg_FILE_AutoCode ON [FILE] AFTER INSERT AS
BEGIN
    UPDATE [FILE] SET MaFile = 'f' + CAST(i.ID AS NVARCHAR(10))
    FROM [FILE] JOIN inserted i ON [FILE].ID = i.ID
    WHERE [FILE].MaFile IS NULL;
END;

-- 9. PROCEDURE: Gán sinh viên vào l?p h?c ph?n
CREATE PROCEDURE sp_ThemSinhVienVaoLHP
    @MaSV INT,
    @MaLHP INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM SINHVIEN_LHP WHERE MaSV=@MaSV AND MaLHP=@MaLHP)
        INSERT INTO SINHVIEN_LHP (MaSV, MaLHP, TrangThai) VALUES (@MaSV, @MaLHP, 1)
END
GO


-- 10. Insert admin test
INSERT INTO USERS (Email, MatKhau, Quyen, TrangThai, HoTen)
VALUES ('admin@ckc.vn', 'admin123', 2, 1, N'Admin CKC');

select*from sinhvien_lhp users

	SELECT * FROM SINHVIEN_LHP
	select*from GIANGVIEN_LHP
SELECT * FROM SINHVIEN_LHP WHERE MaSV = '3';

DBCC CHECKIDENT ('SINHVIEN_LHP', RESEED, 0);


SELECT * FROM GIANGVIEN_LHP WHERE MaGV = 4;
SELECT * FROM GIANGVIEN WHERE MaGV = 12;

select*from GIANGVIEN_SEQ
SELECT * 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'GIANGVIEN';

select*from SINHVIEN_LHP where MaTK=4

SELECT COUNT(*) AS Count
FROM GIANGVIEN
WHERE MaGV = 12;
select*from SINHVIEN
select*from USERS
select*from BOMON
select*from GIANGVIEN_LHP

SELECT * FROM LOPHOCPHAN ORDER BY ID DESC;

SELECT * FROM LOPHOCPHAN ORDER BY ID DESC;
SELECT * FROM GIANGVIEN_LHP ORDER BY ID DESC;

SELECT * FROM GIANGVIEN WHERE MaTK = 7
SELECT * FROM LOPHOCPHAN
SELECT * FROM GIANGVIEN_LHP WHERE MaGV = 4
SELECT * FROM LOPHOCPHAN ORDER BY ID DESC;
SELECT * FROM GIANGVIEN_LHP ORDER BY ID DESC;


SELECT * FROM SINHVIEN_LHP WHERE MaSV =4

SELECT MaGV FROM GIANGVIEN WHERE MaTK = 7
select*from LOPHOCPHAN
select*from MONHOC

SELECT MaGV FROM GIANGVIEN WHERE MaTK = 7

SELECT * FROM GIANGVIEN_LHP WHERE MaLHP = 1;
SELECT * FROM SINHVIEN_LHP WHERE MaLHP = 1;


WHERE svlhp.MaSV = @MaSV AND lhp.TrangThai = 1

DELETE FROM  WHERE MaBaiViet = 'bv9';

SELECT *
FROM LOPHOCPHAN
WHERE MaGV = 5 -- <== dúng MaGV c?a tài kho?n dang nh?p
AND TrangThai = 1
select*from [FILE]

DELETE FROM [FILE] WHERE MaBaiViet = '9';
-- Sau dó
DELETE FROM BaiVIET WHERE MaBaiViet = 'bv9';

SELECT ID FROM SINHVIEN WHERE MaTK = @userId

SELECT 
  lhp.ID,
  lhp.TenLHP,
  lhp.HocKy,
  lhp.NamHoc,
  gv.HoGV + ' ' + gv.TenGV AS TenGV,
  mh.TenMH,
  lh.MaLop
FROM SINHVIEN_LHP svlhp
JOIN LOPHOCPHAN lhp ON svlhp.MaLHP = lhp.ID
JOIN GIANGVIEN gv ON lhp.MaGV = gv.ID
JOIN MONHOC mh ON lhp.MaMH = mh.ID
JOIN LOPHOC lh ON lhp.MaLH = lh.ID
WHERE svlhp.MaSV = maSV AND lhp.TrangThai = 1
SELECT * FROM NOPBAI WHERE MaBaiViet = 24 AND MaSV = 2 AND MaLHP = 8

SELECT * FROM LOPHOCPHAN WHERE TrangThai = 1

SELECT * FROM GIANGVIEN_LHP WHERE MaGV = 5
select*from lophocphan

-- L?y toàn b? GV trong 1 l?p h?c ph?n
SELECT gv.ID AS maGV, gv.HoGV + ' ' + gv.TenGV AS tenGV
FROM GIANGVIEN_LHP glhp
JOIN GIANGVIEN gv ON glhp.MaGV = gv.ID
WHERE glhp.MaLHP = 8

-- L?y toàn b? SV trong 1 l?p h?c ph?n
SELECT sv.ID AS maSV, sv.HoTen AS tenSV
FROM SINHVIEN_LHP slhp
JOIN SINHVIEN sv ON slhp.MaSV = sv.ID
WHERE slhp.MaLHP = @MaLHP

select*from giangvien_lhp